TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1


  max_vel_trans: 0.26
  min_vel_trans: 0.13



  max_vel_theta: 1.0
  min_vel_theta: 0.9
  min_in_place_vel_theta: 0.4




  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5




  yaw_goal_tolerance: 0.05
  xy_goal_tolerance : 0.17
  latch_xy_goal_tolerance : flase


  sim_time: 2.0
  vx_samples: 20
  vtheta_samples : 40
  controller_frequency : 10.0
  oscillation_reset_dist: 0.05

  holonomic_robot: true