obstacle_range: 3.0
raytrace_range: 3.5


footprint: [[183,146],[-183,146],[-183,-146],[183,-146]]


inflation_radius: 1.0
cost_scaling_factor: 3.0


observation_sources: laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, marking: "true" ,clearing: "true"}
