NavfnROS:
  allow_unknown: true
  planner_window_x: 0
  planner_window_y: 0
  default_tolerance: 0
  visualize_potential: true
  
  use_djikstra: true
  use_quadratic: true
  use_grid_path: false
  old_nav_behaviour: true
  

  

