
footprint: [ [0.183,0.146],[-0.183,0.146],[-0.183,-0.146],[0.183,-0.146]]

footprint_padding: 0.03

robot_base_frame: Robot_base

update_frequency: 10 #before: 5.0
publish_frequency: 0.5 #before 0.5

transform_tolerance: 0.9
resolution: 0.06

lehtal_cost_threshold: 100.0



obstacle_layer:  
  enable: true
  observation_sources: scan
  scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
  obstacle_range: 3
  raytrace_range: 3.5
  max_obstacle_height: 1

inflation_layer:
  enable: true
  inflation_radius: 0.55
  cost_scaling_factor: 10.0 #15





# obstacle_range: 2.5
# raytrace_range: 3.0
# footprint: [ [0.183,0.146],[-0.183,0.146],[-0.183,-0.146],[0.183,-0.146]]
# #robot_radius: ir_of_robot
# inflation_radius: 0.55

# observation_sources: laser_scan_sensor 

# laser_scan_sensor: {sensor_frame: LaserScan, data_type: LaserScan, topic: scan, marking: true, clearing: true}




# inflation_layer:
#   enable: true
#   # inflation_radius: 0.55
  # cost_scaling_factor: 10.0 #15



