obstacle_range : 6.0
raytrace_range : 8.5
footprintL : [ [0.183,0.146],[-0.183,0.146],[-0.183,-0.146],[0.183,-0.146]]
map_topic: /map
subscribe_to_updates : true
observation_sources : scan
laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: Robot_base
always_send_full_costmap: true