global_costmap:
  global_frame: map
  rolling_window: true
  width: 20
  height: 20
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  
  

  plugins: 
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}








