local_costmap:
  global_frame: odom
  update_frequency: 1.0
  publish_frequency: 5.0
  
  rolling_window: true
  width: 3
  height: 3
  static_map: false 
  resolution: 0.01


  plugins: 
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}












  